# Generated by Django 4.2.1 on 2023-06-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_comment',
            field=models.BooleanField(default=True),
        ),
    ]
