# Generated by Django 4.2.1 on 2023-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
