# Generated by Django 4.2.1 on 2023-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_friends_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
